//--------------------------------------------------------------------------------------
// VideoShaderEffect.idl
//--------------------------------------------------------------------------------------
import "unknwn.idl";

interface IMFVideoShaderEffect;

//--------------------------------------------------------------------------------------
// IMFVideoShaderEffect
//--------------------------------------------------------------------------------------
[ local, object, uuid(95C8C8D2-14A8-4ED1-8064-9AB562F69E9B),
  helpstring("IMFVideoShaderEffect Interface"), pointer_default(unique) ]

interface IMFVideoShaderEffect : IUnknown{

		HRESULT SetShaderReverseX([in] BOOL);
		HRESULT SetShaderReverseY([in] BOOL);
		HRESULT SetShaderNegatif([in] BOOL);
		HRESULT SetShaderGray([in] BOOL);
		HRESULT SetShaderGrayScale([in] BOOL);
		HRESULT SetShaderColor([in] UINT);
		HRESULT SetShaderContrast([in] FLOAT);
		HRESULT SetShaderSaturation([in] FLOAT);
};

//--------------------------------------------------------------------------------------
// Library and objects
//--------------------------------------------------------------------------------------
[ uuid(7C673E6B-FF72-4E44-BCD6-3B919D2E2506), version(1.0), helpstring("VideoShaderEffect 1.0 Type Library") ]

library VideoShaderEffectLib{

  // MFVideoShaderEffect
  [ uuid(D3200A97-06F5-44A1-A4BC-9137E6A0748F), helpstring("MFVideoShaderEffect Class") ]

  coclass MFVideoShaderEffect{ [default] interface IMFVideoShaderEffect; };
};