//----------------------------------------------------------------------------------------------
// MFNodePlayer_definition.h
//----------------------------------------------------------------------------------------------
#ifndef MFNODEPLAYER_DEFINITION_H
#define MFNODEPLAYER_DEFINITION_H

#define MFNODE_CLASS L"MFNode Player"

const UINT WM_APP_PLAYER_EVENT = WM_APP + 1;

enum CURRENT_SESSION{

	SESSION_NONE,
	SESSION_SCREENSHOT,
	SESSION_HTTP,
	SESSION_FLV,
	SESSION_WAVEMIXER,
	SESSION_RENDERER,
	SESSION_SEQUENCER,
	SESSION_AVCAPTURE,
	SESSION_DXVA2
};

enum CUDA_DECODER{

	CUDA_DECODER_NONE,
	CUDA_DECODER_CUDA
};

enum SHADER_COLOR{ SHADER_COLOR_ORIGINAL, SHADER_COLOR_RED, SHADER_COLOR_GREEN, SHADER_COLOR_BLUE };

enum CHILD_CONTROL{

	CHILD_EDIT_WAVE1,
	CHILD_EDIT_WAVE2,
	CHILD_EDIT_FLV,
	CHILD_EDIT_RENDERER,
	CHILD_EDIT_VIDEO1,
	CHILD_EDIT_VIDEO2,
	CHILD_EDIT_MPEG,
	CHILD_BUTTON_WAVE1,
	CHILD_BUTTON_WAVE2,
	CHILD_BUTTON_FLV,
	CHILD_BUTTON_RENDERER,
	CHILD_BUTTON_VIDEO1,
	CHILD_BUTTON_VIDEO2,
	CHILD_BUTTON_MPEG,
	CHILD_GROUPBOX,
	CHILD_CHECK_REVERSE_X,
	CHILD_CHECK_REVERSE_Y,
	CHILD_CHECK_NEGATIF,
	CHILD_CHECK_GRAY,
	CHILD_CHECK_GRAYSCALE,
	CHILD_RADIO_COLOR,
	CHILD_RADIO_RED,
	CHILD_RADIO_GREEN,
	CHILD_RADIO_BLUE,
	CHILD_RADIO_NOCUDA,
	CHILD_RADIO_CUDA,
	CHILD_TRACKBAR_CONTRAST,
	CHILD_TRACKBAR_SATURATION,
	CHILD_TRACKBAR_DXVA2_BRIGHTNESS,
	CHILD_TRACKBAR_DXVA2_HUE,
	CHILD_TRACKBAR_DXVA2_CONTRAST,
	CHILD_TRACKBAR_DXVA2_SATURATION,
	CHILD_TRACKBAR_DXVA2_NOISE,
	CHILD_TRACKBAR_DXVA2_EDGE,
	CHILD_TRACKBAR_DXVA2_ANAMORPHIC,
	CHILD_END
};

#endif